### ISSUE TITLE
配置项logic_delete是否开启逻辑删除失效

### ISSUE THREAD

**Issue by louchenaishang** [dromara/warm-flow#18]
logic_delete配置false或者删除这个配置项,表里数据仍是逻辑删除状态,期望是能够物理删除。
logic_delete配置成true,logic_delete_value配置成2，逻辑删除字段值还是1.
warmflow版本是1.3.4
![image](https://github.com/user-attachments/assets/d3f8f9a6-847c-450f-87f4-9f89b583ba27)
![image](https://github.com/user-attachments/assets/895a6a5b-fe0a-4b2a-9020-211146395d0d)
![image](https://github.com/user-attachments/assets/ee3696c0-0de9-48ad-b1e3-051a1380c951)
![image](https://github.com/user-attachments/assets/bba6f684-4a12-431b-a24a-28168cdc2e99)

**Comment by minliuhua** [comment]
不支持，mybaits-plus扩展包，内部使用了逻辑删除注解，mp本身配置文件不支持配置多个逻辑删除，只支持一个，所以组件内部必须加上注解，如果业务系统逻辑删除和组件不一样，那组件本身配置不了逻辑删除

如果确实有这个要求，可以重写实体类，删除逻辑删除注解，通过双亲委派原理达到你的目标

![image](https://github.com/user-attachments/assets/b7d83b2a-a947-497d-8abc-cf8015dead78)
